### ISSUE TITLE
New airzone cloud interface. Temperature changing bug

### ISSUE THREAD

**Issue by jmartinezs77** [fjhorrillo/homebridge-airzone-cloud#14]
**Describe The Bug:**
Temperature can’t be modified. When a room is on and try to change temperature, it doesn’t work and an error appears in log. Version 0.2.0 of the plug-in. Using new airzone cloud interface.

**To Reproduce:**
Open a room with airzone on and try to change temperature

**Expected behavior:**
Temperature changes to value provided in home app on iOS.

**Logs:**

```

[9/19/2021, 7:40:18 PM] [AirzoneCloud] SALON1     : Set Characteristic TargetTemperature -> 28.5ºC
[9/19/2021, 7:40:18 PM] [AirzoneCloud] Error calling to AirzoneCloud. Status: 400 Bad Request  Response: {"_id":"commandNotSupportedMode","msg":"Unable to execute the specified command with the actual unit mode","data":{"reason":"Device must be in Stop mode"},"reqId":"da666a14-0d14-4996-8a7e-0839341f55f4#1449172"}
(node:5970) UnhandledPromiseRejectionWarning: Error: Status: 400 Bad Request
    at AirzoneCloudApi._request (/homebridge/node_modules/homebridge-airzone-cloud/src/AirzoneCloudApi.ts:201:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at AirzoneCloudApi._patch (/homebridge/node_modules/homebridge-airzone-cloud/src/AirzoneCloudApi.ts:135:12)
    at AirzoneCloudApi.setTemperature (/homebridge/node_modules/homebridge-airzone-cloud/src/AirzoneCloudApi.ts:425:12)
(node:5970) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)

```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 0.2.0
* **Homebridge Version**: 1.3.4
* **Node.js Version**: 14.17.5
* **NPM Version**: 6.14.14
* **Operating System**: docker on synology

**Comment by gtgGitHub** [comment]
Hi I have installed the new version and I have selected: "New Airzone Cloud" and after reboot everything gone well, it logged in successfully and Websocket Connected, but not Airzone devices on the accessories tab and therefore not device to add to HomeKit.

The Airzone device is Aidoo Wi-Fi for DAIKIN SKY AIR/VRY

Any idea why is not working?

Thanks in advance

**Comment by fjhorrillo** [comment]
Hello @gtgGitHub, at this moment the plugin only admits Airzone or DKN, I am working on Aidoo's support

**Comment by fjhorrillo** [comment]
Added support for Aidoo in version 0.3.0
