### ISSUE TITLE
Confirmation on DKN Cloud NA support?

### ISSUE THREAD

**Issue by PhilM-IT** [fjhorrillo/homebridge-airzone-cloud#15]
**Describe Your Problem:**
I use the "DKN Cloud NA" app which relates to a different URL (dkncloudna.com) than all other solutions that use these adapters. In the app I can control my unit which seems to be powered by the same "airzone" system this plugin supports. None of the existing "system" options appear to work and manually changing the config to the previous mentioned URL doesn't work either.

API integration docs I can find are here: https://backend.daikincomfort.com/docs/default-source/product-documents/residential/manuals/othermanual/im-dknapi.pdf

**Logs:**
[AirzoneCloud] Unable to login to Daikin AirzoneCloud. Request: {"url":"https://dkn.airzonecloud.com/users/sign_in","method":"POST","mode":"cors","headers":{"Content-Type":"application/json;charset=utf-8","User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15"},"body":"{}"} {"size":0,"timeout":0}

**Plugin Config:**
        {
            "name": "AirzoneCloud",
            "system": "https://dkn.airzonecloud.com",
            "login": {
                "email": "",
                "password": ""
            },
            "debug": false,
            "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15",
            "platform": "AirzoneCloud"
        }

**Environment:**
running on raspberry pi 3 B

* **Plugin Version**:v0.2.1
* **Homebridge Version**: v1.3.6
* **Node.js Version**: v16.13.0
* **NPM Version**: v8.1.3
* **Operating System**: Raspbian

**Comment by fjhorrillo** [comment]
Hi @PhilM-IT,

This looks like an Aidoo system, I'm planning to adapt to it, but I don't know how it will be done. I'll work on it as soon as I have time.

Regards.

**Comment by PhilM-IT** [comment]
Thanks for confirming. Happy to test it out once you get around to adjusting the plugin.

**Comment by lavoiesl** [comment]
I'm also interested in support for NA. You can find the documentation at https://backend.daikincomfort.com/docs/default-source/product-documents/residential/manuals/othermanual/im-dknapi.pdf

I can also help with the coding

**Comment by PhilM-IT** [comment]
Not sure if anyone else has tried but I'm unable to get the new Aidoo setup working... the error is also causing homebridge to go into a restart loop and never do online unless I disable the plugin. I'm using the same username and password that works via my iOS app.

[4/1/2022, 8:16:55 AM] [AirzoneCloud] Error calling to AirzoneCloud. Status: 400 Bad Request  Response: {"_id":"userNotExist","msg":"No user registered with provided data","reqId":"a78f8bc9-fe2b-4327-b748-a0bc886dc718#14054857"}
[4/1/2022, 8:16:55 AM] [AirzoneCloud] Error in login Error: Status: 400 Bad Request
[4/1/2022, 8:16:55 AM] Error: Error in login Error: Status: 400 Bad Request
    at AirzoneCloudApi._login (/homebridge/node_modules/homebridge-airzone-cloud/src/AirzoneCloudApi.ts:92:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Function.createAirzoneCloudApi (/homebridge/node_modules/homebridge-airzone-cloud/src/AirzoneCloudApi.ts:63:5)
    at AirzoneCloudHomebridgePlatform.discoverDevices (/homebridge/node_modules/homebridge-airzone-cloud/src/platform.ts:122:28)

**Comment by fjhorrillo** [comment]
Hello @PhilM-IT, what I added is the support via https://m.airzonecloud.com which the plugin use if you chose "New AirzoneCloud".
Your error is regarding this, your user doesn't have access to https://m.airzonecloud.com and I didn't implement it.

I will check the documentation that you provide to check how implement support for it.

**Comment by fjhorrillo** [comment]
Fixed the error handling problem that caused the reboot loop in v0.3.1

**Comment by PhilM-IT** [comment]
Thanks for the confirmation. It seemed like maybe what you did add support for is a different option/service than what we're using.

0.3.1 does seem to fix the crashing loop FYI.

**Comment by AG7GN** [comment]
Thanks very much for this plugin!

I am interested in seeing DKN Cloud NA supported as well. I'm seeing the same behavior as @PhilM-IT in version 0.3.1. I'm happy to test as well.

**Comment by CrazyDymond88** [comment]
I would like to request this as well please and I'm also willing to help test.  With the default settings set to DKN I'm getting "Error calling to AirzoneCloud. Status: 404 Not Found.

**Comment by sundar2012** [comment]
+1 on DKN NA support

**Comment by PhilM-IT** [comment]
@CrazyDymond88 / @sundar2012 try https://github.com/plecong/homebridge-dkncloudna

It supports this, been using for a while now. Seems to work fine.

**Comment by PhilM-IT** [comment]
> @PhilM-IT @lavoiesl Thanks all. I tested that one last night and had some issues - working with the developer directly. I wanted to see if this plugin could be adapted to work.
> 
> P.S. Are our Airzone devices locked to the DKN NA app? my HVAC installer did not explain this - after initial setup I tried resetting and adding to the Airzone app and the device just kept re-appearing in DKN NA.

I'm on iOS and only use dkn NA. From what I could tell the "airzone" branded app won't work with these units.
