### ISSUE TITLE
AirzoneCloud Homebridge Accessoir failed

### ISSUE THREAD

**Issue by Coolant22** [fjhorrillo/homebridge-airzone-cloud#27]
Hello , can you help me ,I have no accessories in the config of Homebridge. What can I do , thanks very much .

            },
            "debug": false,
            "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15",
            "platform": "AirzoneCloud"
        }
    ],
    "accessories": []

[AirzoneCloud] Adding new accessory undefined (UUID: a75646c4-86ef-48a0-ae89-02a2284a2717)
[27/10/2022, 19:37:34] AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:421:11)
    at new PlatformAccessory (/var/lib/homebridge/node_modules/homebridge/src/platformAccessory.ts:70:9)
    at AirzoneCloudHomebridgePlatform.registerDevice (/var/lib/homebridge/node_modules/homebridge-airzone-cloud/src/platform.ts:293:25)
    at AirzoneCloudHomebridgePlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-airzone-cloud/src/platform.ts:150:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by fjhorrillo** [comment]
Hello, it look like your Airzone device/zone doesn't have a name, I didn't think this could happen. How you see it on Airzone App?

**Comment by Coolant22** [comment]
Here is a Picture ![image](https://user-images.githubusercontent.com/116835567/198377441-ccb81f0e-a53d-4c28-b44a-fd95b056de02.jpeg) Thanks

**Comment by fjhorrillo** [comment]
The name of the accessory should be "Zone 1", could you enable debug mode and share the response for the service /api/v1/installations/xxxxx? its look like:
`{
...
    "groups": [
        {
            "name": "Gruppe 1",
            "devices": [
                {
                    "device_id": "999f99f9f99f99999f9fff9e",
                    "meta": {
                        "system_number": 1
                    },
                    "type": "az_system",
                    "ws_id": "AA:AA:AA:AA:AA:AA"
                },
                {
                    "device_id": "999f99f9f99f99999f9fff9f",
                    "meta": {
                        "system_number": 1,
                        "zone_number": 1
                    },
                    "type": "az_zone",
                    "ws_id": "AA:AA:AA:AA:AA:AA",
                    "name": "Zone 1"
                },
...`

**Comment by Coolant22** [comment]
27/10/2022, 21:34:24] [AirzoneCloud] [Websocket] ⬆ ["clear_listeners"]
[27/10/2022, 21:34:24] [AirzoneCloud] Cleaned cached installationId and webserverId
[27/10/2022, 21:34:24] [AirzoneCloud] [Websocket] ⬇ [null]
[27/10/2022, 21:34:24] [AirzoneCloud] [Websocket] ⬆ ["listen_installation", "63592a63b5a0f796ee73ef6a"]
[27/10/2022, 21:34:24] [AirzoneCloud] [Websocket] ⬇ [null]
[27/10/2022, 21:34:24] [AirzoneCloud] [Websocket] ⬇ ["DEVICE_STATE",{"device_id":"635929b043ed6c64aa8c3a79","device_type":"aidoo","ws_id":"28:CC:FF:80:F9:03","status":{"isConnected":true,"ws_connected":true,"speed_type":0,"step":{"fah":1,"celsius":1},"ws_sched_calendar_available":false,"ws_sched_available":true,"range_air_max":{"celsius":30,"fah":86},"range_air_min":{"celsius":15,"fah":59},"machineready":true,"errors":[],"timer":{"value":0,"count":0},"timer_values":[0,30,60,90],"manufacturer":{"_id":8,"text":"Daikin Sky Air / VRV"},"power":false,"aq_quality":null,"aqpm1_0":null,"aqpm2_5":null,"aqpm10":null,"active":false,"fallback_active":false,"warnings":[],"aq_active":null,"aq_mode_conf":null,"aq_mode_values":[],"tt_units":0,"mode":3,"auto_mode":null,"mode_available":[3,4],"setpoint_air_cool":{"celsius":25,"fah":77},"setpoint_air_heat":{"celsius":16,"fah":61},"speed_conf":2,"speed_values":[2,6],"tai_temp":{"celsius":null,"fah":null},"local_temp":{"celsius":19,"fah":66},"setpoint_air_auto":{"celsius":25,"fah":77},"range_sp_cool_air_min":{"celsius":16,"fah":61},"range_sp_cool_air_max":{"celsius":32,"fah":90},"range_sp_hot_air_min":{"celsius":16,"fah":61},"range_sp_hot_air_max":{"celsius":32,"fah":90},"range_sp_auto_air_min":{"celsius":16,"fah":61},"range_sp_auto_air_max":{"celsius":32,"fah":90},"pspeed":50,"block_fantemp":true,"block_drytemp":true,"block_dryspeed":true,"block_autotemp":false,"block_autospeed":false},"ws_type":"ws_aidoo","units":0,"sched_conf":{"step":{"fah":1,"celsius":1},"aq_mode_values":[],"mode_available":[3,4],"speed_values":[2,6],"speed_type":0,"range_sp_cool_air_min":{"celsius":16,"fah":61},"range_sp_cool_air_max":{"celsius":32,"fah":90},"range_sp_hot_air_min":{"celsius":16,"fah":61},"range_sp_hot_air_max":{"celsius":32,"fah":90},"range_sp_auto_air_min":{"celsius":16,"fah":61},"range_sp_auto_air_max":{"celsius":32,"fah":90}}}]
[27/10/2022, 21:34:24] [AirzoneCloud] [Websocket] ⬇ ["DEVICE_STATE_END","63592a63b5a0f796ee73ef6a"]
[27/10/2022, 21:34:24] [AirzoneCloud] The installation status was fully received
[27/10/2022, 21:34:24] [AirzoneCloud] [Fetch] ⬆ Request: GET https://m.airzonecloud.com/api/v1/installations/63592a63b5a0f796ee73ef6a
[27/10/2022, 21:34:24] [AirzoneCloud] [Fetch] ⬇ Response: {"_id":"63592a63b5a0f796ee73ef6b","plugins":{"schedules":{"calendar_ws_ids":[],"activated":false,"week_ws_ids":["28:CC:FF:80:F9:03"],"acs_ws_ids":[]}},"installation_id":"63592a63b5a0f796ee73ef6a","location_id":"63592a63b5a0f796ee73ef68","name":"Wärmepumpe","icon":4,"color":4,"groups":[{"name":"","devices":[{"device_id":"635929b043ed6c64aa8c3a79","type":"aidoo","ws_id":"28:CC:FF:80:F9:03","meta":{"units":0}}],"group_id":"63592a63b5a0f796ee73ef69"}],"scenes":[],"added_at":"2022-10-26T12:38:59.571Z","access_type":"admin","user_id":"6352b0c82fd7af5c2b476eb4"}
[27/10/2022, 21:34:24] [AirzoneCloud] Group: <63592a63b5a0f796ee73ef69>
[27/10/2022, 21:34:24] [AirzoneCloud] AirZone Device: undefined<635929b043ed6c64aa8c3a79>
[27/10/2022, 21:34:24] [AirzoneCloud] Adding new accessory undefined (UUID: a75646c4-86ef-48a0-ae89-02a2284a2717)
[27/10/2022, 21:34:24] AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:421:11)
    at new PlatformAccessory (/var/lib/homebridge/node_modules/homebridge/src/platformAccessory.ts:70:9)
    at AirzoneCloudHomebridgePlatform.registerDevice (/var/lib/homebridge/node_modules/homebridge-airzone-cloud/src/platform.ts:293:25)
    at AirzoneCloudHomebridgePlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-airzone-cloud/src/platform.ts:150:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by fjhorrillo** [comment]
I see that it is an Aidoo system and is a bit different. If it is easier for you, could you change the name without special characters, I mean change "Wärmepumpe" to "Warmepumpe"

**Comment by Coolant22** [comment]
its the same with warmepump[27/10/2022, 21:57:16] [AirzoneCloud] [Fetch] ⬇ Response: {"ws_type":"ws_aidoo","status":{"isConnected":true,"sshost":"skaidoo5.airzonecloud.com","ssport":"443","first_connection_date":"2022-10-26T12:36:53.451Z","pending_ws_schedules_update":false,"connection_date":"2022-10-26 21:53:25 +0200","link_process_active":null,"stat_rssi":-75,"stat_quality":1,"stat_channel":11,"disconnection_date":"2022-10-26 21:53:11 +0200"},"config":{"pin":3531,"mac":"28:CC:FF:80:F9:03","units":0,"ws_sched_available":true,"server_sched_active":true,"ota":false,"tunnel":false,"wsmmgroup":"WSMM1","ws_fw":"3.09","stat_channel":11,"stat_ssid":"Apfelfunk","conn_type":"wifi","country_code":"DE"}}
[27/10/2022, 21:57:16] [AirzoneCloud] [Websocket] ⬆ ["clear_listeners"]
[27/10/2022, 21:57:16] [AirzoneCloud] Cleaned cached installationId and webserverId
[27/10/2022, 21:57:16] [AirzoneCloud] [Websocket] ⬇ [null]
[27/10/2022, 21:57:16] [AirzoneCloud] [Websocket] ⬆ ["listen_installation", "63592a63b5a0f796ee73ef6a"]
[27/10/2022, 21:57:16] [AirzoneCloud] [Websocket] ⬇ [null]
[27/10/2022, 21:57:16] [AirzoneCloud] [Websocket] ⬇ ["DEVICE_STATE",{"device_id":"635929b043ed6c64aa8c3a79","device_type":"aidoo","ws_id":"28:CC:FF:80:F9:03","status":{"isConnected":true,"ws_connected":true,"speed_type":0,"step":{"fah":1,"celsius":1},"ws_sched_calendar_available":false,"ws_sched_available":true,"range_air_max":{"celsius":30,"fah":86},"range_air_min":{"celsius":15,"fah":59},"machineready":true,"errors":[],"timer":{"value":0,"count":0},"timer_values":[0,30,60,90],"manufacturer":{"_id":8,"text":"Daikin Sky Air / VRV"},"power":false,"aq_quality":null,"aqpm1_0":null,"aqpm2_5":null,"aqpm10":null,"active":false,"fallback_active":false,"warnings":[],"aq_active":null,"aq_mode_conf":null,"aq_mode_values":[],"tt_units":0,"mode":3,"auto_mode":null,"mode_available":[3,4],"setpoint_air_cool":{"celsius":25,"fah":77},"setpoint_air_heat":{"celsius":16,"fah":61},"speed_conf":2,"speed_values":[2,6],"tai_temp":{"celsius":null,"fah":null},"local_temp":{"celsius":18.9,"fah":66},"setpoint_air_auto":{"celsius":25,"fah":77},"range_sp_cool_air_min":{"celsius":16,"fah":61},"range_sp_cool_air_max":{"celsius":32,"fah":90},"range_sp_hot_air_min":{"celsius":16,"fah":61},"range_sp_hot_air_max":{"celsius":32,"fah":90},"range_sp_auto_air_min":{"celsius":16,"fah":61},"range_sp_auto_air_max":{"celsius":32,"fah":90},"pspeed":50,"block_fantemp":true,"block_drytemp":true,"block_dryspeed":true,"block_autotemp":false,"block_autospeed":false},"ws_type":"ws_aidoo","units":0,"sched_conf":{"step":{"fah":1,"celsius":1},"aq_mode_values":[],"mode_available":[3,4],"speed_values":[2,6],"speed_type":0,"range_sp_cool_air_min":{"celsius":16,"fah":61},"range_sp_cool_air_max":{"celsius":32,"fah":90},"range_sp_hot_air_min":{"celsius":16,"fah":61},"range_sp_hot_air_max":{"celsius":32,"fah":90},"range_sp_auto_air_min":{"celsius":16,"fah":61},"range_sp_auto_air_max":{"celsius":32,"fah":90}}}]
[27/10/2022, 21:57:16] [AirzoneCloud] [Websocket] ⬇ ["DEVICE_STATE_END","63592a63b5a0f796ee73ef6a"]
[27/10/2022, 21:57:16] [AirzoneCloud] The installation status was fully received
[27/10/2022, 21:57:16] [AirzoneCloud] [Fetch] ⬆ Request: GET https://m.airzonecloud.com/api/v1/installations/63592a63b5a0f796ee73ef6a
[27/10/2022, 21:57:16] [AirzoneCloud] [Fetch] ⬇ Response: {"_id":"63592a63b5a0f796ee73ef6b","plugins":{"schedules":{"calendar_ws_ids":[],"activated":false,"week_ws_ids":["28:CC:FF:80:F9:03"],"acs_ws_ids":[]}},"installation_id":"63592a63b5a0f796ee73ef6a","location_id":"63592a63b5a0f796ee73ef68","name":"Warmepumpe","icon":4,"color":4,"groups":[{"name":"","devices":[{"device_id":"635929b043ed6c64aa8c3a79","type":"aidoo","ws_id":"28:CC:FF:80:F9:03","meta":{"units":0}}],"group_id":"63592a63b5a0f796ee73ef69"}],"scenes":[],"added_at":"2022-10-26T12:38:59.571Z","access_type":"admin","user_id":"6352b0c82fd7af5c2b476eb4"}
[27/10/2022, 21:57:16] [AirzoneCloud] Group: <63592a63b5a0f796ee73ef69>
[27/10/2022, 21:57:16] [AirzoneCloud] AirZone Device: undefined<635929b043ed6c64aa8c3a79>
[27/10/2022, 21:57:16] [AirzoneCloud] Adding new accessory undefined (UUID: a75646c4-86ef-48a0-ae89-02a2284a2717)
[27/10/2022, 21:57:16] AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:421:11)
    at new PlatformAccessory (/var/lib/homebridge/node_modules/homebridge/src/platformAccessory.ts:70:9)
    at AirzoneCloudHomebridgePlatform.registerDevice (/var/lib/homebridge/node_modules/homebridge-airzone-cloud/src/platform.ts:293:25)
    at AirzoneCloudHomebridgePlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-airzone-cloud/src/platform.ts:150:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[27/10/2022, 21:57:16] Got S

**Comment by fjhorrillo** [comment]
Fixed in v0.3.4
