### ISSUE TITLE
Implementar compatibilidad con Airzone DKN EU

### ISSUE THREAD

**Issue by sutterline** [fjhorrillo/homebridge-airzone-cloud#33]
**Describe Your Problem:**
Hola a todos, me gustaría hacer una petición para que el plugin funcionara con Airzone DKN EU a través de su url https://dkneu.airzonecloud.com/

Tengo un controlador dknwserver wifi Sky/VRV de AIRZONE MODELO azai6wscdk1 que controla una máquina Daikin modelo FBQ125B8V3B (es de conductos en un unifamiliar). El sistema funciona a través de la app "Airzone DKN EU" o por la web en https://dkneu.airzonecloud.com/ . 

He intentando poner en marcha el plugin, con los tres sistemas que te proporciona (New AirzoneCloud, AirzoneCloud y DKN), modificando la Base URL a esta https://dkneu.airzonecloud.com/ con mi usuario y contraseña que accede al sistema. No me ha funcionado ninguno de los tres.

También he reseteado el webserver y la conexión a la máquina, y he intentado conectar el webserver a la app Airzone Cloud y la app DKN Cloud a través de bluetooth y también añadiendo la MAC, no me lo añade, me da un mensaje de error "Este Webserver no está aprovisionado". Me supongo que este controlador solo funciona con la app Airzone DKN EU.

El acceso web a dkn y dkneu son distintos: ( https://dkn.airzonecloud.com/#/init/login y https://dkneu.airzonecloud.com/#/auth/login)

**Logs:**
_Sistema New AirzoneCloud_:
[AirzoneCloud] Error in login. FetchError: invalid json response body at https://dkneu.airzonecloud.com/api/v1/auth/login reason: Unexpected token < in JSON at position 0

_Para los dos Sistema DKN y AirzoneCloud tengo los siguientes fallos:_
[AirzoneCloud] Unable to login to Daikin AirzoneCloud. Request: {"url":"https://dkneu.airzonecloud.com/users/sign_in","method":"POST","mode":"cors","headers":{"Content-Type":"application/json;charset=utf-8","User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15"},"body":"{\"email\":\"notimetochill@hotmail.com\",\"password\":\"*********\"}"} {"size":0,"timeout":0}

[AirzoneCloud] Error calling to AirzoneCloud. Status: 404 Not Found

 [AirzoneCloud] Unable to load installations from AirzoneCloud TypeError: Cannot read properties of undefined (reading 'installation_relations')
    at AirzoneCloudDaikin._get_installation_relations (/var/lib/homebridge/node_modules/homebridge-airzone-cloud/src/AirzoneCloudDaikin/AirzoneCloudDaikin.ts:154:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AirzoneCloudDaikin._load_installations (/var/lib/homebridge/node_modules/homebridge-airzone-cloud/src/AirzoneCloudDaikin/AirzoneCloudDaikin.ts:126:43)
    at Function.createAirzoneCloudDaikin (/var/lib/homebridge/node_modules/homebridge-airzone-cloud/src/AirzoneCloudDaikin/AirzoneCloudDaikin.ts:55:5)
    at AirzoneCloudHomebridgePlatform.discoverDaikinDevices (/var/lib/homebridge/node_modules/homebridge-airzone-cloud/src/platform.ts:220:31)

**Plugin Config:**
        {
            "name": "AirzoneCloud",
            "system": "https://dkn.airzonecloud.com",
            "login": {
                "email": "notimetochill@hotmail.com",
                "password": "*********"
            },
            "debug": true,
            "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15",
            "custom_base_url": "https://dkneu.airzonecloud.com",
            "platform": "AirzoneCloud"
        }

_Donde pone "system": "https://dkn.airzonecloud.com", he intentado poner https://dkneu.airzonecloud.com , pero tampoco funciona._

**Screenshots:**

![Modelo máquina](https://github.com/fjhorrillo/homebridge-airzone-cloud/assets/23195992/bc04342b-dcd9-46ec-ad9e-4af7882e814f)
**Environment:**

* **Plugin Version**: homebridge-airzone-cloud v0.3.5
* **Homebridge Version**: homebridge-config-ui-x v4.50.4
* **Node.js Version**: [v18.16.0](https://homebridge.io/w/JTKEF)
* **NPM Version**: 
* **Operating System**: Raspbian GNU/Linux Bullseye (11)

¡Muchas gracias por leerme!

**Comment by fjhorrillo** [comment]
Hola, podrías unirte a discord y así podemos hablar por ese canal, para implementarlo necesitaría de tu ayuda ya que no tengo un sistema como el tuyo con el que hacer las pruebas y validar como funciona su API.

**Comment by sutterline** [comment]
Hola Francisco, cuando quieras hacemos las pruebas. Dime cómo podemos proceder y yo te voy probando todas las cosas. Mi teléfono es el 699 933 551 Juan José.

Estoy también en el discord.


Enviado desde mi iPhone

El 10 mar 2024, a las 19:13, Francisco Javier Horrillo Sancho ***@***.***> escribió:

﻿

Hola, podrías unirte a discord y así podemos hablar por ese canal, para implementarlo necesitaría de tu ayuda ya que no tengo un sistema como el tuyo con el que hacer las pruebas y validar como funciona su API.

**Comment by twoixter** [comment]
Hola @fjhorrillo @sutterline , tengo el mismo equipo con el cloud ese de DKN-EU. Como he visto este hilo paraete he hecho un fork con mis cambios, a ver qué os parece: #54
