### ISSUE TITLE
Error with cool mode in DKN

### ISSUE THREAD

**Issue by fjhorrillo** [fjhorrillo/homebridge-airzone-cloud#7]
**Describe The Bug:**
Node server stops working

**To Reproduce:**
Change state to cold

**Expected behavior:**
Node server keeps running and DKN switches to cold mode

**Logs:**
[15/05/2021, 22:43:00] [Aire Acondicionado] Daikin PB: Set Characteristic TargetHeatingCoolingState -> none
[15/05/2021, 22:43:01] [Aire Acondicionado] mode name "cold" not found
[15/05/2021, 22:43:01] [Aire Acondicionado] Daikin PB: Set Characteristic TargetHeatingCoolingState -> cold
(node:651) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at Device.get mode [as mode] (/usr/local/lib/node_modules/homebridge-airzone-cloud/src/AirzoneCloudDaikin/Device.ts:88:42)
    at Device.str_complete (/usr/local/lib/node_modules/homebridge-airzone-cloud/src/AirzoneCloudDaikin/Device.ts:48:72)
    at Device.turn_on (/usr/local/lib/node_modules/homebridge-airzone-cloud/src/AirzoneCloudDaikin/Device.ts:183:55)
    at AirzoneCloudPlatformAccessoryDaikin.setTargetHeatingCoolingState (/usr/local/lib/node_modules/homebridge-airzone-cloud/src/platformAccessoryDaikin.ts:171:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use node --trace-warnings ... to show where the warning was created)
(node:651)

**Comment by fjhorrillo** [comment]
Fixed in version 0.1.4
